repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: C:/ProgramData/Anaconda3/envs/gaokao_pg/python.exe -m ruff check --fix
        language: system
        types_or: [python, pyi]
    -   id: ruff-format
        name: ruff format
        entry: C:/ProgramData/Anaconda3/envs/gaokao_pg/python.exe -m ruff format
        language: system
        types_or: [python, pyi]
    -   id: mypy
        name: mypy
        entry: C:/ProgramData/Anaconda3/envs/gaokao_pg/python.exe -m mypy
        language: system
        pass_filenames: false
        args:
        - --ignore-missing-imports
        - --no-site-packages
        - --follow-imports=skip
        - gaokaollm_bench/chains
        - gaokaollm_bench/constrains
        - gaokaollm_bench/contracts
        - gaokaollm_bench/flows
        - gaokaollm_bench/graphs
        - gaokaollm_bench/llm
        - gaokaollm_bench/prompts
        - gaokaollm_bench/sandbox
        - gaokaollm_bench/simulator
        - gaokaollm_bench/evaluator
        - gaokaollm_bench/schemas.py
