"""Shared metric names and gate thresholds."""

from __future__ import annotations


METRIC_VAL_ACCURACY = "val_accuracy"
METRIC_VAL_MACRO_F1 = "val_macro_f1"
METRIC_VAL_LOSS = "val_loss"
METRIC_TRAIN_ACCURACY = "train_accuracy"
METRIC_TRAIN_LOSS = "train_loss"

BEST_VAL_MACRO_F1 = "best_val_macro_f1"
BEST_VAL_ACCURACY = "best_val_accuracy"
BEST_VAL_TOP3_ACCURACY = "best_val_top3_accuracy"
BEST_VAL_LOSS = "best_val_loss"

DEFAULT_SELECTION_METRIC = METRIC_VAL_MACRO_F1
DEFAULT_PROMOTION_MACRO_F1 = 0.758751771732541
DEFAULT_PROMOTION_ACCURACY = 0.7710843373493976
STRICT_ABLATION_PROMOTION_MACRO_F1 = 0.6862
STRICT_ABLATION_PROMOTION_ACCURACY = 0.7088

DEFAULT_VAL_BENCHMARK_REVIEW_THRESHOLD = 0.35
VAL_BENCHMARK_THRESHOLD_SWEEP = [0.20, 0.35, 0.50]
